spring:
  application:
    name: haibackend

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000

  jpa:
    defer-datasource-initialization: true
    hibernate:    
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false

  sql:
    init:
      mode: always
      encoding: utf-8
      data-locations: classpath:ai_person_data.sql, classpath:discussion_data.sql 

logging:
  level:
    org.springframework.jdbc.datasource.init: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

aws:
  credentials:
    access-key-id: ${AWS_ACCESS_KEY_ID}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${CLOUD_AWS_REGION:ap-northeast-2}
  bedrock:
    model:
      chat: ${AWS_BEDROCK_CHAT_MODEL:anthropic.claude-3-haiku-20240307-v1:0}
    knowledge-base:
      id: ${AWS_BEDROCK_KB_ID}
      model-arn: ${AWS_BEDROCK_KB_MODEL_ARN}
    prompt:
      debate-topic: ${AWS_BEDROCK_DEBATE_TOPICS_PROMPT_ARN}

fastapi:
  base-url: ${FASTAPI_BASE_URL:http://localhost:8000}

server:
  port: ${SERVER_PORT}

jwt:
  secret: ${JWT_SECRET_KEY}
